AWSTemplateFormatVersion: 2010-09-09
Description: Route 53 - CloudFront Distribution for ELB
Resources:
  CloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - DomainName:
            Fn::ImportValue: SeoulELBDNSName # ELB arn
          Id: 
            Fn::ImportValue: SeoulELBID #ELB ID
          CustomOriginConfig:
            OriginProtocolPolicy: http-only
        Enabled: true
        Aliases:
          - www.ticketing.pw
          - ticketing.pw
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:833326266803:certificate/5be258cf-b86e-4f39-83dc-f676014ef4bb # 인증서 arn, 반드시 us-east-1에 있어야 지원됨
          MinimumProtocolVersion: TLSv1 #(SSLv3 | TLSv1 | TLSv1.1_2016 | TLSv1.2_2018 | TLSv1.2_2019 | TLSv1_2016 사용가능)
          SslSupportMethod: sni-only
        DefaultCacheBehavior: 
          AllowedMethods: 
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - PATCH
            - POST
            - DELETE
          CachePolicyId: !Ref CachePolicy
          Compress: true
          SmoothStreaming: false
          TargetOriginId:
            Fn::ImportValue: SeoulELBID
          ViewerProtocolPolicy: redirect-to-https # 클라이언트가 http로 요청해도 https로 리다이렉트한다.
      Tags:
        - Key: Name
          Value: Ticket-CloudFront-ELB
          
  CachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties: 
      CachePolicyConfig: 
        DefaultTTL: 0
        MaxTTL: 1
        MinTTL: 0
        Name: TicketCachePolicy
        ParametersInCacheKeyAndForwardedToOrigin: 
          CookiesConfig: 
            CookieBehavior: all
          EnableAcceptEncodingGzip: true
          HeadersConfig: 
            HeaderBehavior: none
          QueryStringsConfig: 
            QueryStringBehavior: all


# Route 53 Record 생성
  Route53www:
    Type: AWS::Route53::RecordSet
    Properties: 
      AliasTarget: 
        DNSName: !GetAtt CloudFront.DomainName
        HostedZoneId: Z2FDTNDATAQYW2 # Alias 사용시 전용 ID 값, 고정된 값이므로 수정 X
    #  GeoLocation: # 지리 위치 기반 라우팅일 때 설정
      HostedZoneId: Z0579297BG1S4H8QSFM6 # 호스팅 영역 ID
      Name: www.ticketing.pw
      Type: A

  Route53:
    Type: AWS::Route53::RecordSet
    Properties: 
      AliasTarget: 
        DNSName: !GetAtt CloudFront.DomainName
        HostedZoneId: Z2FDTNDATAQYW2 # Alias 사용시 전용 ID 값, 고정된 값이므로 수정 X
    #  GeoLocation: # 지리 위치 기반 라우팅일 때 설정
      HostedZoneId: Z0579297BG1S4H8QSFM6 # 호스팅 영역 ID
      Name: ticketing.pw
      Type: A
#  Route53:
#    Type: AWS::Route53::RecordSet
#    Properties: 
#      AliasTarget: 
#        DNSName: !GetAtt CloudFront.DomainName
#        HostedZoneId: Z04526451NRGVHUC50XUH # 호스팅 영역 ID
    #  GeoLocation: # 지리 위치 기반 라우팅일 때 설정
#     HostedZoneId: Z04526451NRGVHUC50XUH
#      Name: ticketing.pw
#      Type: A
  
          
